### ISSUE TITLE
Unable to visit any website or search anything.

### ISSUE THREAD

**Issue by MMzF7** [AbyssServices/Abyss-Web#2]
Hi i am on ubuntu 22.04, with Node.js v18.19.0 npm 10.2.3
I am unable to visit,search anything.
![Screenshot_20240111_151807](https://github.com/AbyssServices/Abyss-Web/assets/104319020/d655c49c-23b4-43da-bd78-23d15be62ae3)

**Comment by impaxton** [comment]
please join the discord at discord.gg/goabyss and open a ticket, i will assist you there

**Comment by myschoolisass** [comment]
this also happens when you use https://github.com/whos-evan/elixir, just refresh / reload frame and it should work
